### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by whosdatdev** [invu/movieo#16]
Hi, I cannot build the solution because the projects ChreneLib and CButtonLib are referenced but not in the git repo. Where can i get them?

**Comment by invu** [comment]
I will update the repo soon.

**Comment by invu** [comment]
Hi @whosdatdev,

After some revisions on the project, it has occurred to me that some work is going to be needed before I push a (somewhat) stable release to the repo as the project I have locally is undergoing maintenance due to some updates/upgrades I'm performing. I will, however, be working on this occasionally but no eta. Please feel free to work at it yourself, the dependencies your having problems with are simple, the ChreneLib is just a custom watermark using the TextBox control, so you can either find it on online or use an alternative and the CButtonLib can be found on most of my projects found on my profile and somewhere on the web too. Shouldn't be too much of a problem, don't hesitate to email me at 
> bettercodes1 -at -gmail.com

Best Regards,
invu

**Comment by whosdatdev** [comment]
Alright, I'll try when I have some spare time, thanks

**Comment by invu** [comment]
Everything's been fixed and updated, but I'm unable to commit to the repo at the moment. If you're still interested in forking the project then email me and I'll send it over to you. Thanks.
